#!/bin/bash
contact : adit@chrootid.com

function init_program {
        clear
        OPENAI_API_KEY=$(cat /root/data/openai_api_key)
        GREEN='\033[1;32m';
        YELLOW='\033[1;33m';
        BGREEN='\e[30;48;5;82m';
        BYELLOW='\e[30;48;5;11m';
        NC='\033[0m';
        BNC='\e[30;48;5;0m';
        echo -e "${BGREEN} AI   ${BNC}${GREEN}: Send a message...${NC}";
}

function clear_session {
        echo > /tmp/openai
}

function chat_request {
        curl -s https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d "{\"model\": \"gpt-3.5-turbo\", \"messages\": [{ \"role\": \"user\", \"content\": \"$INQUERY\"}]}"
}

function nc (){
        echo -e " exit ${NC}"
}

function main_program {
        trap "nc;exit" SIGINT
        while true;do
                echo -ne "${BYELLOW} User ${BNC}${YELLOW}: ";read -r INQUERY
                chat_request | jq ".choices[] | .message | .content"|sed 's/\\n/\n/g' > /tmp/openai
                echo -e "${BGREEN} AI   ${BNC}${GREEN}: $(cat /tmp/openai)${NC}"
                clear_session
        done
}
init_program
main_program
